### ISSUE TITLE
Does type_doc do something?

### ISSUE THREAD

**Issue by dvic** [dashbitco/nimble_options#100]
If I'm not mistaken, the `type_doc` option seems to be unused in the project? Maybe I'm mistaken, but I can't see any effect of using this option.

**Comment by josevalim** [comment]
Please send a PR to remove it? :)

**Comment by dvic** [comment]
Sure, no problem :) But is there (another) way to modify the outputted type spec / docs ;)? In this case i'm trying to `type_doc` a function. Or is this considered out of scope for now?

**Comment by josevalim** [comment]
which Elixir code would you be expecting it to produce?

**Comment by josevalim** [comment]
Oh, I see what you mean. It is something to replace the default type doc option. Yeah, an option to make that actually be used will be welcome too. Your call, please tell me which one to merge. :)

**Comment by dvic** [comment]
Hah okay, then I'll work on making it work ;)

**Comment by aselder** [comment]
Was just about to mention this... Thanks @dvic
