### ISSUE TITLE
Allowing nil values in non-required options?

### ISSUE THREAD

**Issue by spatrik** [dashbitco/nimble_options#108]
I've been using NimbleOptions for a while and there is one thing I can't figure out how to handle. Sometimes I want to have an option that doesn't have to be set. For example, I have a function that can query a database in different ways. I want to have two options: `name_contains` and `category`, both should be `string`, but I want to be able to do a query with only one of these options (or both).

I can set `require` to `false`, but then I need a default. But if I set `default` to `nil`, the validation will fail, since `nil` isn't a string. 

I can of course set the type to `type: {:or, [:string, :atom]}`, but then I allow every atom and it doesn't really communicate what I actually mean.

Since this has happened almost every time I've used NimbleOptions I'm wondering if I'm missing something? If not, would it be a good idea to add an option for `allow_nil`? Or add `:nil` as a type, so I can at least do `{:or, [:string, :nil]}` to not allow all atoms and more clearly communicate that nil is ok?

**Comment by josevalim** [comment]
If we add an option (@whatyouhide decides), we should consider calling it `nilable` or `allow_nil`.

**Comment by whatyouhide** [comment]
Yeah, let's have `allow_nil: true | false` then. I think it's quite common to have this use case, and it's a really tiny addition to this library, so let's go for it 👍 

Take your time with the PR @spatrik, no worries, and thanks in advance!

**Comment by josevalim** [comment]
Devils advocate: if we make `nil` a type, then `{:or, [:string, nil]}` is actually less typing then `allow_nil: true`?

**Comment by whatyouhide** [comment]
Fair point, but if we use `:allow_nil` we can also take advantage of it for documentation. Is that something we could do? Like automatically documenting that "this option can be set to `nil`" or something. It also makes the type itself cleaner IMO, but that's a weaker argument.

**Comment by josevalim** [comment]
I mean, specifying the type `| nil` should be readable enough, no? Otherwise there is not much purpose in printing typespecs? :)

**Comment by whatyouhide** [comment]
Fair enough. @spatrik let's go with `nil` as a type then!

**Comment by spatrik** [comment]
If I understand you correctly, you prefer doing `type: {:or, [:string, nil]}`, right? 

One thing I would like with having an `allow_nil` option is that the generated documentation could then say "* `field`: (`String.t/0` or `nil`)". Now the type for an  `:or` is empty. 

I'm guessing it's also possible to check if the type is `{:or, [something, nil]}`, only two options, and one of them is nil, and output the docs then. 

I haven't used the typespecs generation at all, but I really like that I can get a lot of information in the docs, with very little work. Even if I don't actually write any documentation, I get the name of the option and the type "for free", just by writing the validation code. For docs for a non-public app, that hits a sweet spot for me between writing documentation and speed.
