### ISSUE TITLE
How should we call the spec/definition?

### ISSUE THREAD

**Issue by josevalim** [dashbitco/nimble_options#11]
Currently we call it "spec" but it is a very overloaded term and people will confuse it with libraries that actually use specs for option validation.

I proposed "definition" in an earlier PR but @whatyouhide proposed "schema". Do you have any preferences? /cc @wojtekmach @msaraiva

**Comment by wojtekmach** [comment]
Agreed on renaming, in fact it could be an interesting feature to create a _type_ off this data (that would complement the docs we are already generating) and so having a _type_ and _spec_ would be confusing. Both "definition" and "schema" sounds good to me.

**Comment by msaraiva** [comment]
`schema` sound more appropriate to me.

**Comment by josevalim** [comment]
Let’s ship with schema then!
