### ISSUE TITLE
A question on error message of `validate/2` 

### ISSUE THREAD

**Issue by c4710n** [dashbitco/nimble_options#127]
When trying the example code in `README.md`:

```elixir
definition = [
  connections: [
    type: :non_neg_integer,
    default: 5
  ],
  url: [
    type: :string,
    required: true
  ]
]

options = []
NimbleOptions.validate(options, definition)
```

It returns:
```elixir
{:error,
 %NimbleOptions.ValidationError{
   message: "required :url option not found, received options: [:connections]",
   key: :url,
   value: nil,
   keys_path: []
 }}
```

We provide `options` as `[]`,

But, the `message:` line shows that the received options are `[:connections]`.

---

It seems that the received options considers the default values, but should we consider the default values when showing the received options?

**Comment by josevalim** [comment]
Yes, looks like a bug to me! PRs welcome!
