### ISSUE TITLE
Handling secure options

### ISSUE THREAD

**Issue by anthonator** [dashbitco/nimble_options#132]
In certain scenarios, validation error messages should not reveal sensitive information. For example, if a validation error message includes the value of an option, and that value is sensitive, it could pose a security risk.

For example, if an API key is used as input and a validation error occurs, the error message might include the API key, which could lead to unintended exposure of sensitive information.

I could see adding a `:redact` schema option to prevent sensitive values from being included in validation error messages. This option would ensure that:
  - Sensitive values are not displayed in validation error messages.
  - The `NimbleOptions.ValidationError` struct hides sensitive values when inspected.
  
This would enhance security by ensuring sensitive information is not exposed in error messages and would help prevent accidental leakage of sensitive data in logs or user-facing error messages.

**Comment by whatyouhide** [comment]
I think this could work yeah. Any chance you want to send a PR? 🙃

**Comment by anthonator** [comment]
I can give it a shot!

**Comment by anthonator** [comment]
See #133

**Comment by whatyouhide** [comment]
Closing in favor of the PR (#133).
