### ISSUE TITLE
Validate certain params and allow to have extra ones

### ISSUE THREAD

**Issue by rockneurotiko** [dashbitco/nimble_options#136]
We are doing a internally wrapper of a library (`Req`), where we'll require certain params to be passed but others will be just the same as Req, we wanted to use NimbleOptions to validate the required params but allow any other param, and I don't know if it's not possible, it's a bug, or I don't know how to build the schema for this behaviour.

Here is a simple example of what we wanted:

``` elixir
schema = [name: [type: :atom, required: true], *: [type: :any]]
opts = [name: :some_name, other_value: 2]
NimbleOptions.validate(opts, schema)
```

With this schema it doesn't validate the `:name` option at all, I guess `*:` has priority:

``` elixir
iex(11)> NimbleOptions.validate([], schema)
{:ok, []}
iex(12)> NimbleOptions.validate([name: "a"], schema)
{:ok, [name: "a"]}
```

**Comment by wojtekmach** [comment]
I'm -1 on allowing arbitrary option names.

I think you can do the following today:

```elixir
{known_options, other_options} = Keyword.split(options, [:a, :b])
NimbleOptions.validate(known_options, schema)
```

Btw, in Req you can grab the options Req knows of: `Req.new().registered_options` and you can assign an any type to them.

It's not documented at the moment but I'd be happy to add a public API: Req.Request.registered_option_names(req)`, a PR would be appreciated.

I'm going to close this but happy to continue the conversation.

**Comment by KettelBear** [comment]
I would like to continue the conversation to provide another potential use case, that maybe isn't exactly the same, but is closely related.

Working at a larger company, there is another team entirely that manages the environment and its variables in AWS. With that said, the `schema` may change in the process of updating code which could be the removal of an option in the schema. Removing an option doesn't remove the assignment of the environment variable, and then `validate_unknown_options/2` triggers with an error. This doesn't work well with CI/CD pipelines.

After thoroughly inspecting, it appears as though the many recursive calls do not easily permit a way to avoid `validate_unknown_options/2`. But I at least wanted to get the discussion opened up again, and get some input.

Thoughts?

**Comment by whatyouhide** [comment]
@KettelBear I’m not sure I’m following. Can this separate team expose the option names, so that you can do something like

```elixir
{known_options, other_options} = Keyword.split(options, OtherTeamsCode.env_option_names())
NimbleOptions.validate(known_options, schema)
```

?

**Comment by KettelBear** [comment]
Not quite a possibility in my organization, but let me take a step back to gain more understanding.

Now that I've had a few more days to think about it, I cannot figure out what benefit or function `validate_unknown_options/2` provides. I don't see a problem if a configuration has extra keys that are not part of the schema.

What situation is it supposed to catch and prevent? I would like to understand this before I try and continue down this path.

**Comment by whatyouhide** [comment]
Main issue would be this:

```elixir
schema = [concurrency: [type: :integer, default: 100]]

NimbleOptions.validate!([concurency: 3], schema)
#=> [concurrency: 100]
```

Can't catch wrong options, typos, or anything like that. I’m not sure why, if someone is exposing the validation, they couldn't also expose the set of keys that are valid. It might help understand the issue better.

**Comment by KettelBear** [comment]
Okay, great. I understand the typos part.

It isn't about keys that are valid or invalid. It is about keys being valid, then being removed from the schema, but not the environment, thus making them invalid now.

However, the more I thought about it, the more it does not make sense to make any changes. Thank you for entertaining this conversation.

**Comment by westmark** [comment]
> If you have a schema, that won't be more efficient than doing `Keyword.keys(schema)`, right?

..ehmm.. I guess not 😅
