### ISSUE TITLE
Hiding options with "doc: false"

### ISSUE THREAD

**Issue by whatyouhide** [dashbitco/nimble_options#23]
Sometimes some options are internal but you still want to validated them. What do you folks think if we add support for `doc: false` to hide an option? I think that aligns with how we do docs in general.

**Comment by josevalim** [comment]
Sounds good!

**Comment by msaraiva** [comment]
Sounds good to me too!

**Comment by whatyouhide** [comment]
Awesome, will work on this as soon as #21 is good to go and merged 👍
