### ISSUE TITLE
Add option for `accepted_values` or `allowed_values` ?

### ISSUE THREAD

**Issue by praveenperera** [dashbitco/nimble_options#30]
What do you think about having an option to validate against and set number of options?

For example:

```elixir
definition = [
  status: [
    type: :atom,
    allowed_values: [:waiting, :started, :finished],
    default: :waiting
  ],
]
```

**Comment by wojtekmach** [comment]
this is already supported via `:one_of`, e.g.:

    batch_mode: [type: {:one_of, [:flush, :bulk]}]]
