### ISSUE TITLE
Type spec generation

### ISSUE THREAD

**Issue by michallepicki** [dashbitco/nimble_options#32]
I took a look at whether it would be possible and I think it is. Macros don't get expanded inside `@type` for some reason so I didn't get this working:
```
require NimbleOptions.Type
@type opts :: NimbleOptions.Type.generate(schema)
```

But I think this could work:
```
require NimbleOptions.Type
NimbleOptions.Type.generate(opts, schema)
```

Is there a plan to add ability to generate a `@type` spec from the schema? Would that be a welcome addition in this project? I could publish a separate package instead

**Comment by josevalim** [comment]
Currently no plans. Thanks for checking though!

**Comment by michallepicki** [comment]
Can I use `nimble_options` in the package name? Something like `nimble_options_type`

**Comment by josevalim** [comment]
Sure!

**Comment by michallepicki** [comment]
For anyone interested, I have a WIP project, [tests](https://github.com/michallepicki/nimble_options_type/blob/master/lib/nimble_options_type.ex) show what it generates. Overall seems fine, I am getting the usual fast-enough feedback cycle from dialyzer for catching option keys typos etc. Because NimbleOptions works on keyword lists (and not maps), Dialyzer cannot enforce requiredness per field.

I may add some escape hatch option to pass custom type definitions, it could also allow to support recursive options I think.
