### ISSUE TITLE
Complex example of `one_of`? 

### ISSUE THREAD

**Issue by martinstreicher** [dashbitco/nimble_options#36]
I posted a question about Nimble Options' `one_of` [here](https://elixirforum.com/t/nimbleoptions-and-the-one-of-operator/31443). Is it possible to express nested options as arguments of `one_of`? Is there an example I can reference? I'd be happy to post a PR for the docs if someone can explain what `choices` can be in the usage  `{:one_of, choices}`

**Comment by josevalim** [comment]
Not really. You would have to use use custom validation instead.

**Comment by martinstreicher** [comment]
Thanks. It looks like the \`choices\` must be literal values.
