### ISSUE TITLE
Hex release with new rich error messages

### ISSUE THREAD

**Issue by zachdaniel** [dashbitco/nimble_options#39]
I could really use the new rich error messages change in hex (so I can release my hex packages since you can't use GH dependencies in hex).

**Comment by josevalim** [comment]
@whatyouhide are you ok with a v0.3.0 release?

**Comment by whatyouhide** [comment]
@josevalim I would prefer to wait and have a way to return all errors, so that if we have to break compatibility, we do so only once. I can look at that this weekend.

**Comment by zachdaniel** [comment]
Yeah, that makes sense.

**Comment by whatyouhide** [comment]
We decided to leave the returning-all-errors feature for next release. v0.3.0 is out on Hex!
