### ISSUE TITLE
Proposal: add `integer` type

### ISSUE THREAD

**Issue by zachdaniel** [dashbitco/nimble_options#42]
I was surprised to find that only `:non_neg_integer` and `:pos_integer` were supported, but this seems like a pretty common type that should be included by default. Thoughts?

**Comment by josevalim** [comment]
Do you have an use case for it? If so, then please send a PR, otherwise we can wait until someone does. :)

**Comment by zachdaniel** [comment]
Yep! I’ll submit a PR, thanks :)
