### ISSUE TITLE
Feature request: return all errors

### ISSUE THREAD

**Issue by axelson** [dashbitco/nimble_options#45]
Broken off from #44

**Comment by Jcambass** [comment]
Should we try to add this in a backwards compatible manner or is it worth a version bump to change the structure of the existing `ValidationError` and keep the `validate` method?

**Comment by whatyouhide** [comment]
I just released v1.0.0, and it seems like this wasn't widely requested. Since the type system is going to shake things up for this library, I'd rather not undertake the effort here and just not implement this for the time being. Thanks everyone! 💟
