### ISSUE TITLE
Recursive type regression on validation

### ISSUE THREAD

**Issue by shikanime** [dashbitco/nimble_options#65]
As I was looking for a recursive type, for my use case to validate a recursive tree. I discovered that #3 added recursive type support using the lazy function but no longer works. I suspect a regression when a dead code cleanup took place in #26.
As the documentation generation has a different implementation, the @options_schema in the NimbleOptions moduledoc has worked since but the validation don't.

Using one of the unit test as example:

```elixir
defmodule Foo do
  def recursive_schema() do
    [
      *: [
        type: :keyword_list,
        keys: [
          type: [
            type: :atom,
            required: true,
            doc: "The type of the option item."
          ],
          required: [
            type: :boolean,
            default: false,
            doc: "Defines if the option item is required."
          ],
          keys: [
            type: :keyword_list,
            doc: "Defines which set of keys are accepted.",
            keys: &Foo.recursive_schema/0
          ],
          default: [
            doc: "The default."
          ]
        ]
      ]
    ]
  end
end
```

```elixir
> NimbleOptions.validate([], Foo.recursive_schema())

** (ArgumentError) invalid schema given to NimbleOptions.validate/2. Reason: expected :keys to be a keyword list, got: &Foo.recursive_schema/0 (in options [:*, :keys, :keys])
    (nimble_options 0.3.5) lib/nimble_options.ex:233: NimbleOptions.validate/2
```

```elixir
> NimbleOptions.docs(Foo.recursive_schema())        

"  * `:type` - Required. The type of the option item.\n\n  * `:required` - Defines if the option item is required. The default value is `false`.\n\n  * `:keys` - Defines which set of keys are accepted.\n\n  * `:default` - The default.\n\n"
```

But as this is not officially supported in the documentation, I don't know if it is a feature or a bug.

**Comment by Shikanime** [comment]
My use case was on validating an OpenAPI configuration that may have some recursive types like Schema object type like:

```elixir
config :openapi,
  # ...
  spec:  [
    paths: [
      "/foo": [
        type: "object",
        properties: [
          bar: [
            type: "object",
            properties: [
              baz: [
                type: "string"]]]]]]]
```

Based on the specification, a schema is used to define a type of value such as string, number but also nested object.

**Comment by whatyouhide** [comment]
Closing this since you can implement manual validation of a recursive type by doing custom validators and recursive calls to `NimbleOptions.validate/2`. Thanks @shikanime! 💟
