### ISSUE TITLE
Options schema seems to be validated for each call

### ISSUE THREAD

**Issue by lud** [dashbitco/nimble_options#69]
Hello, 

What do you think about validating the schema once, so we can define an `@attribute` and then directly call the validation with a valid schema?

Thank you

**Comment by josevalim** [comment]
This is a great call. Can you please send a PR? We could have something like `NimbleOptions.new!`, that returns a struct with validated options and if a validated struct is given to NimbleOptions.validate, we don't validate it again.

**Comment by whatyouhide** [comment]
Agreed, nice idea. Let's do it 👍

**Comment by lud** [comment]
Hi @josevalim & @whatyouhide , this is my proposal : https://github.com/dashbitco/nimble_options/pull/70

**Comment by josevalim** [comment]
Beautiful, closing this in favor of the PR!
