### ISSUE TITLE
Basic types: which ones are nice?

### ISSUE THREAD

**Issue by whatyouhide** [dashbitco/nimble_options#8]
I think we are missing at least:

  * `:string` (or `:binary`?)
  * `:boolean`

I think those are pretty common and they showed up in the first time I tried out nimble_options on a work project. Thoughts?

**Comment by josevalim** [comment]
Yes, PRs are welcome! I would go with `:string` to keep it higher level.

**Comment by whatyouhide** [comment]
Turns out, they were just not documented, sorry 😄 https://github.com/dashbitco/nimble_options/pull/9

**Comment by msaraiva** [comment]
> Turns out, they were just not documented, sorry

Haha. I'm the one who should say sorry then 🙂
