### ISSUE TITLE
Feature Request: Support run-time-evaluated Defaults

### ISSUE THREAD

**Issue by jtrees** [dashbitco/nimble_options#97]
Occasionally, providing a default at compile-time just doesn't work. For example, if I want to provide a timestamp and have it default to `DateTime.utc_now()`, I can't with nimble options. Instead I have to default to `nil` and manually handle it (or something like that).

It would be cool if run-time-evaluated defaults were supported. Perhaps they can be provided as functions, like so?

```elixir
schema = [
  at: [
    default: &DateTime.utc_now/0,
    doc: "when foo took place"
  ]
]
```

**Comment by josevalim** [comment]
In those cases, I suggest to setting the default after validating. That’s because you can’t realistically set all defaults. Sometimes they depend on other options, in other inputs, etc. :) thanks!
